### ISSUE TITLE
3 propostes

### ISSUE THREAD

**Issue by mastergun** [GeriatricProcessingUniversity/GPU#6]
include storytelling, transmedia platforms and a first game mechanics proposal

"Serà ideal que cada un plantejem una proposta i despres les posem en comu i llimem aspereses"

**Comment by SpykeReload** [comment]
https://docs.google.com/document/d/10vnOwe8t12iEKrmFHC1KTUxtx1YE8krvhuc09whyj1Y/edit?usp=sharing

**Comment by mastergun** [comment]
estic incluind la meva proposta dins del document. demà la posarem a discusió
